"""user add config

Revision ID: 30d48d0056b1
Revises: 9a8f38fd9a6a
Create Date: 2024-01-06 19:47:55.650908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30d48d0056b1'
down_revision: Union[str, None] = '9a8f38fd9a6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('user', sa.Column('config', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'config')
    op.alter_column('order', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
