"""update order 2.1

Revision ID: 6d566b553b3a
Revises: 97d592da891b
Create Date: 2024-02-20 23:51:14.583054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d566b553b3a'
down_revision: Union[str, None] = '97d592da891b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('thumbnailUrl', sa.String(), nullable=True))
    op.alter_column('order', 'video_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('order', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('order', 'length',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('order', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('order', 'length',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('order', 'video_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('order', 'thumbnailUrl')
    # ### end Alembic commands ###
