"""update order 1.4

Revision ID: 8a081c7ca2bd
Revises: a47ebf5efb5f
Create Date: 2024-02-20 22:05:26.664948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a081c7ca2bd'
down_revision: Union[str, None] = 'a47ebf5efb5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('username', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_constraint('order_user_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'user', ['username'], ['username'])
    op.drop_column('order', 'user_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.add_column('order', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_user_id_fkey', 'order', 'user', ['user_id'], ['id'])
    op.drop_column('order', 'username')
    # ### end Alembic commands ###
