"""user new column

Revision ID: 8effc10ee330
Revises: f4a3a78b158b
Create Date: 2024-01-03 16:13:41.418329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8effc10ee330'
down_revision: Union[str, None] = 'f4a3a78b158b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('twitch_user_id', sa.String(), nullable=False))
    op.add_column('user', sa.Column('twitch_access_token', sa.String(), nullable=False))
    op.add_column('user', sa.Column('twitch_refresh_token', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'twitch_refresh_token')
    op.drop_column('user', 'twitch_access_token')
    op.drop_column('user', 'twitch_user_id')
    # ### end Alembic commands ###
